### ISSUE TITLE
Errors in README.md

### ISSUE THREAD

**Issue by Chetan-Goyal** [Ixyk-Wolf/SpotifyOverlay#2]
There are some problems like heading not properly written, steps not written in new line, important text in bold etc in README.md file. 

Can you please assign me this issue? I will make a pull request fixing all of these problems.

**Comment by Ixyk-Wolf** [comment]
Sure, you can fix those issues. I have been trying and it looks alright in my markdown editor but it wouldn't work here.

I would love for you to make a pull request and will assign you on!
